///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String dashboardIcon = 'assets/images/dashboard.svg';
  static const String libraryIcon = 'assets/images/library.svg';
  static const String moreIcon = 'assets/images/more.svg';
  static const String watchIcon = 'assets/images/watch.svg';
}
